// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef atiNetFtUI_h
#define atiNetFtUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Box.H>

class atiNetFtUI {
public:
  atiNetFtUI();
  Fl_Double_Window *DisplayWindow;
private:
  void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  Fl_Value_Output *Force[3];
  Fl_Value_Output *Torque[3];
private:
  void cb_Rebias_i(Fl_Button*, void*);
  static void cb_Rebias(Fl_Button*, void*);
public:
  Fl_Button *FTLogger;
private:
  void cb_FTLogger_i(Fl_Button*, void*);
  static void cb_FTLogger(Fl_Button*, void*);
public:
  bool DoClose; 
  static void CloseWindow_CB(Fl_Widget*, void *caller);
  bool DoLogClicked; 
  bool DoRebias; 
};
#endif
